services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-backend
    network_mode: "host"
    environment:
    - POSTGRES_URI=postgresql://test_user:postgres@localhost:5433/langgraph_db

    # ports:
    #   - "8000:8000"
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  ollama_data: